default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgres://postgres:password@db:5432/tsundoku_development" %>

test:
  <<: *default
  url: <%= (ENV['DATABASE_URL'] || "postgres://postgres:password@db:5432/tsundoku_development").gsub('development', 'test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>